# Generated by Django 5.0.1 on 2024-02-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='edenaitoken',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
